# Generated by Django 4.0.4 on 2022-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name_of_state', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_confirmed_cases', models.IntegerField()),
                ('death', models.IntegerField()),
                ('cured', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
            ],
        ),
    ]
